## copied from https://github.com/bbolker/fitsir/blob/master/.travis.yml
## https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
r: devel
cache: packages

warnings_are_errors: false

## this saves time; it also stops us from getting R CMD check warnings
## (which get promoted to errors/build failures unless we specify
## "warnings_are_errors: false" here ...)
r_build_args: "--no-build-vignettes"

notifications:
    email:
    on_success: change
    on_failure: change
